# Generated by Django 2.2.5 on 2019-12-08 18:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Storie',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_user_id', models.IntegerField()),
                ('to_user_id', models.IntegerField()),
                ('text', models.CharField(max_length=300, null=True)),
                ('sticker_uuid', models.UUIDField(blank=True, null=True)),
                ('music_uuid', models.UUIDField(blank=True, null=True)),
                ('back', models.IntegerField(choices=[(1, 'white'), (2, 'red'), (3, 'yellow'), (4, 'green'), (5, 'black')])),
            ],
        ),
    ]
